[13/Jan/2018 10:47:56] "GET /index/ HTTP/1.1" 200 1298
[13/Jan/2018 10:47:56] "GET /static/css/index.css HTTP/1.1" 404 1770
[13/Jan/2018 10:47:56] "GET /static/js/index.js HTTP/1.1" 404 1764
[13/Jan/2018 10:55:04] "GET /index/?nsukey=39T1ln%2BMzaMkvTsgUpZEwCXoM9rEl%2BFs0nucxSt53O33roV0caVQxoOGeYlIRzygKIs02oS7hWxLKwxzXzT0mqx5H3D1Vpce9%2F9swIBgRkIifev1v%2F%2BdbQpuAn%2FymDcsNB7vhzWL%2BSUTW5%2BEof0J2IKWsjvVnKdaBeFj4NIO0J0PYdJoCrYZzbWJROR3vfCm1tF0CU8eCYKOOLXkUemaTA%3D%3D HTTP/1.1" 200 1298
[13/Jan/2018 10:55:04] "GET /index/?nsukey=39T1ln%2BMzaMkvTsgUpZEwCXoM9rEl%2BFs0nucxSt53O33roV0caVQxoOGeYlIRzygKIs02oS7hWxLKwxzXzT0mqx5H3D1Vpce9%2F9swIBgRkIifev1v%2F%2BdbQpuAn%2FymDcsNB7vhzWL%2BSUTW5%2BEof0J2IKWsjvVnKdaBeFj4NIO0J0PYdJoCrYZzbWJROR3vfCm1tF0CU8eCYKOOLXkUemaTA%3D%3D HTTP/1.1" 200 1298
[13/Jan/2018 10:55:04] "GET /static/js/index.js HTTP/1.1" 404 1764
[13/Jan/2018 10:55:04] "GET /static/css/index.css HTTP/1.1" 404 1770
[13/Jan/2018 10:55:06] "GET /index/?nsukey=39T1ln%2BMzaMkvTsgUpZEwCXoM9rEl%2BFs0nucxSt53O33roV0caVQxoOGeYlIRzygKIs02oS7hWxLKwxzXzT0mqx5H3D1Vpce9%2F9swIBgRkIifev1v%2F%2BdbQpuAn%2FymDcsNB7vhzWL%2BSUTW5%2BEof0J2IKWsjvVnKdaBeFj4NIO0J0PYdJoCrYZzbWJROR3vfCm1tF0CU8eCYKOOLXkUemaTA%3D%3D HTTP/1.1" 200 1298
[13/Jan/2018 10:55:06] "GET /static/css/index.css HTTP/1.1" 404 1770
[13/Jan/2018 10:55:06] "GET /static/js/index.js HTTP/1.1" 404 1764
[13/Jan/2018 10:56:03] "GET /index/?nsukey=39T1ln%2BMzaMkvTsgUpZEwCXoM9rEl%2BFs0nucxSt53O33roV0caVQxoOGeYlIRzygKIs02oS7hWxLKwxzXzT0mqx5H3D1Vpce9%2F9swIBgRkIifev1v%2F%2BdbQpuAn%2FymDcsNB7vhzWL%2BSUTW5%2BEof0J2IKWsjvVnKdaBeFj4NIO0J0PYdJoCrYZzbWJROR3vfCm1tF0CU8eCYKOOLXkUemaTA%3D%3D HTTP/1.1" 200 1298
[13/Jan/2018 10:56:03] "GET /static/js/index.js HTTP/1.1" 404 1764
[13/Jan/2018 11:08:23] "GET /index/ HTTP/1.1" 200 1298
[13/Jan/2018 11:08:23] "GET /static/css/index.css HTTP/1.1" 404 1770
[13/Jan/2018 11:08:23] "GET /static/js/index.js HTTP/1.1" 404 1764
[13/Jan/2018 11:08:25] "GET /index/ HTTP/1.1" 200 1298
[13/Jan/2018 11:08:25] "GET /static/css/index.css HTTP/1.1" 404 1770
[13/Jan/2018 11:08:25] "GET /static/js/index.js HTTP/1.1" 404 1764
Not Found: /
[13/Jan/2018 12:39:35] "GET / HTTP/1.1" 404 2581
[13/Jan/2018 13:44:01] code 400, message Bad request syntax ('\x00\x00\x00TZ\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x04\x010I\x00\x00\x00\x00\x80\x0b\xa8\xc0\x00\x0c)t F\x07\x00tsXrcsXYs9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00bbXcsXctst\x00\x00\x00\x00\x00\x00')
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/site-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 25: ordinal not in range(128)
Logged from file basehttp.py, line 124
[13/Jan/2018 15:16:27] "GET /index/ HTTP/1.1" 200 1298
[13/Jan/2018 15:16:28] "GET /static/css/index.css HTTP/1.1" 404 1770
[13/Jan/2018 15:16:28] "GET /static/js/index.js HTTP/1.1" 404 1764
Internal Server Error: /wx/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view piaowu.views.wx didn't return an HttpResponse object. It returned None instead.
[13/Jan/2018 15:21:06] "GET /wx/ HTTP/1.1" 500 54893
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, piaowu, sessions.
Run 'python manage.py migrate' to apply them.
January 13, 2018 - 10:47:42
Django version 1.11, using settings 'yuhuatai.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[13/Jan/2018 15:22:53] "GET /wx/ HTTP/1.1" 302 0
[13/Jan/2018 15:23:07] "GET /static/js/index.js HTTP/1.1" 404 1764
[13/Jan/2018 15:23:07] "GET /static/css/index.css HTTP/1.1" 404 1770
[13/Jan/2018 15:23:42] "GET /wx/?nsukey=ffJEKcS9X5xlzfvzAkQ7W1VRel5zB%2B0MEjmTecX1PIu2a%2F%2FdM8znneYbHUmoAB%2FYWCUz6JwUewzKnFNMtglVoF1MHRmNq03jOmlpDBNWWtoDa9l5VvwT1dBy4fyt%2Byb6byDLBvQ44s%2FdqX87tQx5PS%2BVihWSSnr4e2sGOvsP2Lv2eVEcDR68r6FMquezWSELJv5JbIWrCFJeXYDsedRH1w%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:23:42] "GET /wx/?nsukey=ffJEKcS9X5xlzfvzAkQ7W1VRel5zB%2B0MEjmTecX1PIu2a%2F%2FdM8znneYbHUmoAB%2FYWCUz6JwUewzKnFNMtglVoF1MHRmNq03jOmlpDBNWWtoDa9l5VvwT1dBy4fyt%2Byb6byDLBvQ44s%2FdqX87tQx5PS%2BVihWSSnr4e2sGOvsP2Lv2eVEcDR68r6FMquezWSELJv5JbIWrCFJeXYDsedRH1w%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:23:43] "GET /wx/?nsukey=ffJEKcS9X5xlzfvzAkQ7W1VRel5zB%2B0MEjmTecX1PIu2a%2F%2FdM8znneYbHUmoAB%2FYWCUz6JwUewzKnFNMtglVoF1MHRmNq03jOmlpDBNWWtoDa9l5VvwT1dBy4fyt%2Byb6byDLBvQ44s%2FdqX87tQx5PS%2BVihWSSnr4e2sGOvsP2Lv2eVEcDR68r6FMquezWSELJv5JbIWrCFJeXYDsedRH1w%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:24:37] "GET /wx HTTP/1.1" 301 0
[13/Jan/2018 15:24:41] "GET /wx/?nsukey=ffJEKcS9X5xlzfvzAkQ7W1VRel5zB%2B0MEjmTecX1PIu2a%2F%2FdM8znneYbHUmoAB%2FYWCUz6JwUewzKnFNMtglVoF1MHRmNq03jOmlpDBNWWtoDa9l5VvwT1dBy4fyt%2Byb6byDLBvQ44s%2FdqX87tQx5PS%2BVihWSSnr4e2sGOvsP2Lv2eVEcDR68r6FMquezWSELJv5JbIWrCFJeXYDsedRH1w%3D%3D HTTP/1.1" 302 0
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, piaowu, sessions.
Run 'python manage.py migrate' to apply them.
January 13, 2018 - 15:22:14
Django version 1.11, using settings 'yuhuatai.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[13/Jan/2018 15:26:28] "GET /wx/?nsukey=9jATpV4YW5WJjcyyQpkbUyD1mlW6vQk%2FK%2BysF1I%2FbuTNi77tO0cHFeT3C3USdLPcSooiwwgPvl1KfZROQupoTUHrt%2BCY%2FlBmz6V3MpSnDfymqkdrzZjt9cUNNOgNDEL5JMXSdKUjMQJIPq%2F2DA2jBNMaKCR%2F6qrKV7bT7YeqbWHk6k5%2BeFE7tCl8wev5sJYzBHreEiVZEfbhjjN9msLJQg%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:26:28] "GET /wx/?nsukey=9jATpV4YW5WJjcyyQpkbUyD1mlW6vQk%2FK%2BysF1I%2FbuTNi77tO0cHFeT3C3USdLPcSooiwwgPvl1KfZROQupoTUHrt%2BCY%2FlBmz6V3MpSnDfymqkdrzZjt9cUNNOgNDEL5JMXSdKUjMQJIPq%2F2DA2jBNMaKCR%2F6qrKV7bT7YeqbWHk6k5%2BeFE7tCl8wev5sJYzBHreEiVZEfbhjjN9msLJQg%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:26:28] "GET /wx/?nsukey=9jATpV4YW5WJjcyyQpkbUyD1mlW6vQk%2FK%2BysF1I%2FbuTNi77tO0cHFeT3C3USdLPcSooiwwgPvl1KfZROQupoTUHrt%2BCY%2FlBmz6V3MpSnDfymqkdrzZjt9cUNNOgNDEL5JMXSdKUjMQJIPq%2F2DA2jBNMaKCR%2F6qrKV7bT7YeqbWHk6k5%2BeFE7tCl8wev5sJYzBHreEiVZEfbhjjN9msLJQg%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:27:14] "GET /wx HTTP/1.1" 301 0
[13/Jan/2018 15:27:14] "GET /wx/ HTTP/1.1" 302 0
[13/Jan/2018 15:27:28] "GET /wx/?nsukey=9jATpV4YW5WJjcyyQpkbUyD1mlW6vQk%2FK%2BysF1I%2FbuTNi77tO0cHFeT3C3USdLPcSooiwwgPvl1KfZROQupoTUHrt%2BCY%2FlBmz6V3MpSnDfymqkdrzZjt9cUNNOgNDEL5JMXSdKUjMQJIPq%2F2DA2jBNMaKCR%2F6qrKV7bT7YeqbWHk6k5%2BeFE7tCl8wev5sJYzBHreEiVZEfbhjjN9msLJQg%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:42:32] "GET /index/ HTTP/1.1" 200 1298
[13/Jan/2018 15:42:32] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 15:42:32] "GET /static/js/index.js HTTP/1.1" 404 1759
Not Found: /favicon.ico
[13/Jan/2018 15:42:32] "GET /favicon.ico HTTP/1.1" 404 2627
[13/Jan/2018 15:43:35] "GET /wx?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 301 0
Not Found: /
[13/Jan/2018 15:43:35] "GET / HTTP/1.1" 404 2576
Not Found: /
[13/Jan/2018 15:43:35] "GET / HTTP/1.1" 404 2576
[13/Jan/2018 15:43:36] "GET /wx/?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:43:41] "GET /wx?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:43:41] "GET /wx/?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:43:42] "GET /wx?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:43:42] "GET /wx/?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:43:50] "GET /wx/?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:44:23] "GET /wx HTTP/1.1" 301 0
[13/Jan/2018 15:44:35] "GET /wx?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:44:35] "GET /wx?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:44:42] "GET /wx/?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:47:13] "GET /wx?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:47:13] "GET /wx/?nsukey=zL29mVwk3PXk9KIn6or%2F7ktJDY4dUov0abTbw7MdtFSfu6v5iAJjrMjemK38k8V6feDwWQH3mralDtClPGFwXuGLkwtiL8nVxHJATQeS93pj0aTxWSpudJvv0mwh9rzc8luQ43SVT%2F0bCE2B%2Fp5nZu9domRl15iiMZ%2Ftw7a0rQn21yIV6Ln7q1os65ydb5fFSWh29%2FBn%2BImNu13jPsbg4w%3D%3D HTTP/1.1" 302 0
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, piaowu, sessions.
Run 'python manage.py migrate' to apply them.
January 13, 2018 - 15:42:25
Django version 1.11, using settings 'yuhuatai.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[13/Jan/2018 15:48:16] "GET /wx?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 301 0
Not Found: /
[13/Jan/2018 15:48:16] "GET / HTTP/1.1" 404 2576
Not Found: /
[13/Jan/2018 15:48:16] "GET / HTTP/1.1" 404 2576
[13/Jan/2018 15:48:16] "GET /wx/?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 302 0
Not Found: /
[13/Jan/2018 15:48:17] "GET / HTTP/1.1" 404 2576
[13/Jan/2018 15:48:17] "GET /wx?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:48:17] "GET /wx/?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:48:18] "GET /wx?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:48:18] "GET /wx/?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:48:25] "GET /wx_in/?code=0712Sf1V0CJbwU1CcnZU0yWk1V02Sf1-&state=123&nsukey=bGswfWrDNKNHIZdAz2q50D7%2BMDQ%2BTV4w5%2BdNPz3lrYeKyvjPyCH301S687ckaLsbuK2%2BFcEIiyKKVVbVaXx88xPDr77mH2O6pB1v4yFiGkjUcJdlIR9ZNDcm%2Fc%2BkeBiG6fgwB2oDQh9MQw5sHb7Cf3GMDUna7allFAh3qxivRM2UG3Q7wdjEQQoeR%2BYAk5f19%2FtXxAuPwpXqEUOI7Ppymw%3D%3D HTTP/1.1" 200 1391
[13/Jan/2018 15:48:25] "GET /wx_in/?code=0712Sf1V0CJbwU1CcnZU0yWk1V02Sf1-&state=123&nsukey=bGswfWrDNKNHIZdAz2q50D7%2BMDQ%2BTV4w5%2BdNPz3lrYeKyvjPyCH301S687ckaLsbuK2%2BFcEIiyKKVVbVaXx88xPDr77mH2O6pB1v4yFiGkjUcJdlIR9ZNDcm%2Fc%2BkeBiG6fgwB2oDQh9MQw5sHb7Cf3GMDUna7allFAh3qxivRM2UG3Q7wdjEQQoeR%2BYAk5f19%2FtXxAuPwpXqEUOI7Ppymw%3D%3D HTTP/1.1" 200 1391
[13/Jan/2018 15:48:25] "GET /static/js/index.js HTTP/1.1" 404 1759
[13/Jan/2018 15:48:25] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 15:48:26] "GET /wx_in/?code=0712Sf1V0CJbwU1CcnZU0yWk1V02Sf1-&state=123&nsukey=bGswfWrDNKNHIZdAz2q50D7%2BMDQ%2BTV4w5%2BdNPz3lrYeKyvjPyCH301S687ckaLsbuK2%2BFcEIiyKKVVbVaXx88xPDr77mH2O6pB1v4yFiGkjUcJdlIR9ZNDcm%2Fc%2BkeBiG6fgwB2oDQh9MQw5sHb7Cf3GMDUna7allFAh3qxivRM2UG3Q7wdjEQQoeR%2BYAk5f19%2FtXxAuPwpXqEUOI7Ppymw%3D%3D HTTP/1.1" 200 1391
[13/Jan/2018 15:48:26] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 15:48:26] "GET /static/js/index.js HTTP/1.1" 404 1759
Not Found: /favicon.ico
[13/Jan/2018 15:48:26] "GET /favicon.ico HTTP/1.1" 404 2627
[13/Jan/2018 15:48:50] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:48:50] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:48:52] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:48:52] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:48:52] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:48:52] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:48:52] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:48:52] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:48:53] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:48:53] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:48:54] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:48:54] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:48:54] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:48:54] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:49:05] "GET /wx_in/?code=021K4zUj1WFVZk0hbvVj1eizUj1K4zUN&state=123&nsukey=EVbH%2BGjQzvFz5Gm3FUQdyZCOH7BXYarvfJEPgbEPLcavR5l2GbOxSIY4ROxZzVoDKo6VfHTnE%2BytVs8k05yoUELbL9saHWU%2BakdGWZETo6xQ2HpQfayhBz7RaJWAjylctIeoQLyDZfxSfKSJszJH1K9GP0DBDbh7bWO%2FMevZev06wdWSe4GA%2FiBoYY4E5gu8dGlZWfjvYt2IrOo3DpN0lA%3D%3D HTTP/1.1" 200 1391
[13/Jan/2018 15:49:05] "GET /wx_in/?code=021K4zUj1WFVZk0hbvVj1eizUj1K4zUN&state=123&nsukey=EVbH%2BGjQzvFz5Gm3FUQdyZCOH7BXYarvfJEPgbEPLcavR5l2GbOxSIY4ROxZzVoDKo6VfHTnE%2BytVs8k05yoUELbL9saHWU%2BakdGWZETo6xQ2HpQfayhBz7RaJWAjylctIeoQLyDZfxSfKSJszJH1K9GP0DBDbh7bWO%2FMevZev06wdWSe4GA%2FiBoYY4E5gu8dGlZWfjvYt2IrOo3DpN0lA%3D%3D HTTP/1.1" 200 1391
[13/Jan/2018 15:49:05] "GET /static/js/index.js HTTP/1.1" 404 1759
[13/Jan/2018 15:49:05] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 15:49:06] "GET /wx_in/?code=021K4zUj1WFVZk0hbvVj1eizUj1K4zUN&state=123&nsukey=EVbH%2BGjQzvFz5Gm3FUQdyZCOH7BXYarvfJEPgbEPLcavR5l2GbOxSIY4ROxZzVoDKo6VfHTnE%2BytVs8k05yoUELbL9saHWU%2BakdGWZETo6xQ2HpQfayhBz7RaJWAjylctIeoQLyDZfxSfKSJszJH1K9GP0DBDbh7bWO%2FMevZev06wdWSe4GA%2FiBoYY4E5gu8dGlZWfjvYt2IrOo3DpN0lA%3D%3D HTTP/1.1" 200 1391
[13/Jan/2018 15:49:06] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 15:49:06] "GET /static/js/index.js HTTP/1.1" 404 1759
Not Found: /favicon.ico
[13/Jan/2018 15:49:06] "GET /favicon.ico HTTP/1.1" 404 2627
[13/Jan/2018 15:49:16] "GET /wx?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:49:18] "GET /wx/?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:49:50] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:49:52] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:49:54] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:51:57] "GET /wx?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:51:58] "GET /wx/?nsukey=dVe10bZHZm5ly56STgdXGYbUYwOlgjYK6W2unGxJS5jRnvfXJelkHb%2B9cNsrH2fG206D03207aDLhRvsztWkH%2FqlOM8cvx0yG2az3pJacniJzrVr5iexQ5Z8CjIvDgMfxDX97EUqC9DG%2BkCBfwKhIRw5M21%2BPD3aHuoe2G5DjI7Oan7o5jtFVvkyCoOQcV0fVrvV8Xc%2B3cGdjemPzpXm6A%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:52:33] "GET /wx?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:52:34] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:52:34] "GET /wx/?nsukey=X1VKIhuYuLas6f9ML6tmLvz8hLt0nwlBakU7jGPO90%2Bl9AJCOrZM%2BzoHa6dwps0We%2BNeNYXDmw9wJfgKQNh%2Fje%2BGYSqRcm%2BbezmMETum1hTjaWzSAw1FPOc5uyf%2FyOUhygZ%2BTdjAu8nKdAsd08QQuMngGXmeW8ISkOtbXTPGjjiv5gyf6D77Xab8yCouH7jYl14fegNbs5Lidjnl%2BwCMdw%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:56:10] "GET /wx?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:56:10] "GET /wx/?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:56:11] "GET /wx?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:56:11] "GET /wx/?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:56:12] "GET /wx?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:56:12] "GET /wx/?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:56:20] "GET /wx_in/?code=061bxSXo1rT6Qp0XrXVo1CBYXo1bxSXF&state=123&nsukey=rtb%2BE9LK0UpZpnkxYXx3P%2BGEhS8ZF2zZkmls2Ckr%2FpPdmqxc9sZdtVsbUuNnIVwTjs9pRpgNH1NCQujtoUM%2BnygyaDZtTmpSGMRxdvHUFy%2BDHBeNGBHZDxaZ0AFUNHIkaNgjB9530MbqBxC5lqoZGihb9EOBd6j3Vspab5ucdTT6SHXKw%2FSB72k%2BsUKScWOap5ArSj0Le2196d0VyvnXaA%3D%3D HTTP/1.1" 200 1389
[13/Jan/2018 15:56:21] "GET /wx_in/?code=061bxSXo1rT6Qp0XrXVo1CBYXo1bxSXF&state=123&nsukey=rtb%2BE9LK0UpZpnkxYXx3P%2BGEhS8ZF2zZkmls2Ckr%2FpPdmqxc9sZdtVsbUuNnIVwTjs9pRpgNH1NCQujtoUM%2BnygyaDZtTmpSGMRxdvHUFy%2BDHBeNGBHZDxaZ0AFUNHIkaNgjB9530MbqBxC5lqoZGihb9EOBd6j3Vspab5ucdTT6SHXKw%2FSB72k%2BsUKScWOap5ArSj0Le2196d0VyvnXaA%3D%3D HTTP/1.1" 200 1389
[13/Jan/2018 15:56:21] "GET /static/js/index.js HTTP/1.1" 404 1759
[13/Jan/2018 15:56:21] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 15:56:23] "GET /wx_in/?code=061bxSXo1rT6Qp0XrXVo1CBYXo1bxSXF&state=123&nsukey=rtb%2BE9LK0UpZpnkxYXx3P%2BGEhS8ZF2zZkmls2Ckr%2FpPdmqxc9sZdtVsbUuNnIVwTjs9pRpgNH1NCQujtoUM%2BnygyaDZtTmpSGMRxdvHUFy%2BDHBeNGBHZDxaZ0AFUNHIkaNgjB9530MbqBxC5lqoZGihb9EOBd6j3Vspab5ucdTT6SHXKw%2FSB72k%2BsUKScWOap5ArSj0Le2196d0VyvnXaA%3D%3D HTTP/1.1" 200 1389
[13/Jan/2018 15:56:23] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 15:56:23] "GET /static/js/index.js HTTP/1.1" 404 1759
Not Found: /favicon.ico
[13/Jan/2018 15:56:23] "GET /favicon.ico HTTP/1.1" 404 2627
[13/Jan/2018 15:57:10] "GET /wx?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:57:11] "GET /wx?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:57:12] "GET /wx/?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 302 0
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, piaowu, sessions.
Run 'python manage.py migrate' to apply them.
January 13, 2018 - 15:47:41
Django version 1.11, using settings 'yuhuatai.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
#################################JJJJJJ
#################################JJJJJJ
#################################JJJJJJ
#################################JJJJJJ
#################################JJJJJJ
#################################JJJJJJ
#################################JJJJJJ
#################################JJJJJJ
#################################JJJJJJ
[13/Jan/2018 15:58:41] "GET /wx?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:58:41] "GET /wx/?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 302 0
Not Found: /
[13/Jan/2018 15:58:41] "GET / HTTP/1.1" 404 2576
[13/Jan/2018 15:58:41] "GET /wx?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 301 0
Not Found: /
[13/Jan/2018 15:58:41] "GET / HTTP/1.1" 404 2576
[13/Jan/2018 15:58:41] "GET /wx/?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:58:42] "GET /wx?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:58:42] "GET /wx/?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:58:44] "GET /wx_in/?code=071WkUD71wG70T1HEpG71zBjE71WkUDy&state=123&nsukey=ZEf4LW9zRwimBCijz1ruA6S5r7Ad6Noq1ZU%2F981ccRm39qpbAmR%2BtS5axwIBUgWJnt9BU8ZKj1v7iPzo1oOz0DPumQQpLlhTvpslHQRzgfeDGRQqBh6Um8%2Butlw5%2FjJDzumtfck0N0nQ8NWTsAcsWt%2B9NL6swk%2F1%2BGCuq%2BoSLMYK%2F3PuxP%2B5AfOcyTpWe4eYxdh8WXdvImhYvcv0cTAlNw%3D%3D HTTP/1.1" 200 1413
[13/Jan/2018 15:58:44] "GET /wx_in/?code=071WkUD71wG70T1HEpG71zBjE71WkUDy&state=123&nsukey=ZEf4LW9zRwimBCijz1ruA6S5r7Ad6Noq1ZU%2F981ccRm39qpbAmR%2BtS5axwIBUgWJnt9BU8ZKj1v7iPzo1oOz0DPumQQpLlhTvpslHQRzgfeDGRQqBh6Um8%2Butlw5%2FjJDzumtfck0N0nQ8NWTsAcsWt%2B9NL6swk%2F1%2BGCuq%2BoSLMYK%2F3PuxP%2B5AfOcyTpWe4eYxdh8WXdvImhYvcv0cTAlNw%3D%3D HTTP/1.1" 200 1389
[13/Jan/2018 15:58:44] "GET /static/js/index.js HTTP/1.1" 404 1759
[13/Jan/2018 15:58:44] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 15:58:46] "GET /wx_in/?code=071WkUD71wG70T1HEpG71zBjE71WkUDy&state=123&nsukey=ZEf4LW9zRwimBCijz1ruA6S5r7Ad6Noq1ZU%2F981ccRm39qpbAmR%2BtS5axwIBUgWJnt9BU8ZKj1v7iPzo1oOz0DPumQQpLlhTvpslHQRzgfeDGRQqBh6Um8%2Butlw5%2FjJDzumtfck0N0nQ8NWTsAcsWt%2B9NL6swk%2F1%2BGCuq%2BoSLMYK%2F3PuxP%2B5AfOcyTpWe4eYxdh8WXdvImhYvcv0cTAlNw%3D%3D HTTP/1.1" 200 1389
[13/Jan/2018 15:58:46] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 15:58:46] "GET /static/js/index.js HTTP/1.1" 404 1759
Not Found: /favicon.ico
[13/Jan/2018 15:58:46] "GET /favicon.ico HTTP/1.1" 404 2627
[13/Jan/2018 15:58:52] "GET /wx/?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:59:40] "GET /wx?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 15:59:42] "GET /wx/?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 15:59:47] "GET /wx/?nsukey=fcJ29gPxFPAbi4w4PBzIbGFV1LkaIv9weKzC5%2F6m45bluJRwZotItkhiPw3J0%2FsSE6RPHnXj3J1Cia0wQVa7vDcC95t7GUt92vS%2F%2Fc7XjozqPYqs5jUbYso6nHD1Y4zAT7bzQhRDUYrX0njGjwitzmZDLJx8undN%2FbyUOh2%2F3tEkjPyq671s72AN%2FnyNx1K8Rg98hpJGcMWdaFY%2F00%2FsEA%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 16:01:35] "GET /wx/?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 16:02:20] "GET /wx?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 16:02:21] "GET /wx/?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 16:02:23] "GET /wx/?nsukey=rK0ecLOS%2B7SgTyK8bxm2%2F%2F6N68QuVYd7mC8jMVH9xJ1cXYto8UqimfSD4Jy7K1kwZVDqoNDoufAdH1lCSjYlPfqeFrGeX%2F8INeUhazrs6sqbWxeSuh3jRDgyeTI4cISCFasRFeEk6kORGAfsKtnJzCvmOgMENGRj%2BO4bI4jQGzqjOpMuqxaHxmN40nCHtJI09saep4Yfj4RDhg3K5kSgzQ%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 16:06:37] "GET /wx?nsukey=EJZeq%2BTL13jFWBXSUMQ2KD5ubKJyGdvIZUP%2BR0rVW0EDAzOX61Xnp2tTK%2BeYuSm92BetKcR92fc7doXrJIYOQ8XIgyNIeyz5sYkN3NLZeFuHb86rx0NjwvvdgDk3t2Q2h%2FEbXMv6Vly4r246ZX%2FBbM6akDD0AUXwnP1XhBVIK%2BBNuKJRByLKDBNRqdtvrCm0kjGBdwRn204wdf7miUqbzA%3D%3D HTTP/1.1" 301 0
Not Found: /
[13/Jan/2018 16:06:37] "GET / HTTP/1.1" 404 2576
[13/Jan/2018 16:06:37] "GET /wx/?nsukey=EJZeq%2BTL13jFWBXSUMQ2KD5ubKJyGdvIZUP%2BR0rVW0EDAzOX61Xnp2tTK%2BeYuSm92BetKcR92fc7doXrJIYOQ8XIgyNIeyz5sYkN3NLZeFuHb86rx0NjwvvdgDk3t2Q2h%2FEbXMv6Vly4r246ZX%2FBbM6akDD0AUXwnP1XhBVIK%2BBNuKJRByLKDBNRqdtvrCm0kjGBdwRn204wdf7miUqbzA%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 16:06:38] "GET /wx?nsukey=EJZeq%2BTL13jFWBXSUMQ2KD5ubKJyGdvIZUP%2BR0rVW0EDAzOX61Xnp2tTK%2BeYuSm92BetKcR92fc7doXrJIYOQ8XIgyNIeyz5sYkN3NLZeFuHb86rx0NjwvvdgDk3t2Q2h%2FEbXMv6Vly4r246ZX%2FBbM6akDD0AUXwnP1XhBVIK%2BBNuKJRByLKDBNRqdtvrCm0kjGBdwRn204wdf7miUqbzA%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 16:06:38] "GET /wx/?nsukey=EJZeq%2BTL13jFWBXSUMQ2KD5ubKJyGdvIZUP%2BR0rVW0EDAzOX61Xnp2tTK%2BeYuSm92BetKcR92fc7doXrJIYOQ8XIgyNIeyz5sYkN3NLZeFuHb86rx0NjwvvdgDk3t2Q2h%2FEbXMv6Vly4r246ZX%2FBbM6akDD0AUXwnP1XhBVIK%2BBNuKJRByLKDBNRqdtvrCm0kjGBdwRn204wdf7miUqbzA%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 16:06:39] "GET /wx?nsukey=EJZeq%2BTL13jFWBXSUMQ2KD5ubKJyGdvIZUP%2BR0rVW0EDAzOX61Xnp2tTK%2BeYuSm92BetKcR92fc7doXrJIYOQ8XIgyNIeyz5sYkN3NLZeFuHb86rx0NjwvvdgDk3t2Q2h%2FEbXMv6Vly4r246ZX%2FBbM6akDD0AUXwnP1XhBVIK%2BBNuKJRByLKDBNRqdtvrCm0kjGBdwRn204wdf7miUqbzA%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 16:06:39] "GET /wx/?nsukey=EJZeq%2BTL13jFWBXSUMQ2KD5ubKJyGdvIZUP%2BR0rVW0EDAzOX61Xnp2tTK%2BeYuSm92BetKcR92fc7doXrJIYOQ8XIgyNIeyz5sYkN3NLZeFuHb86rx0NjwvvdgDk3t2Q2h%2FEbXMv6Vly4r246ZX%2FBbM6akDD0AUXwnP1XhBVIK%2BBNuKJRByLKDBNRqdtvrCm0kjGBdwRn204wdf7miUqbzA%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 16:06:46] "GET /wx_in/?code=011fmWss1g6kWo09HSps15hZss1fmWs6&state=123&nsukey=H30p1V0dFRzfolPFOP7VUf689MIGgjPjs72j48HiAOJTocP%2BJDhiiAHdAXoAJkI4TqU0dF4yDR73%2FFyR3gfYv9LNjZvug2MJPdhyTL1C4HTvZ0ddgKPDh6JNn92FnA7nvPU87qBcdaamimiAEm%2FyCSSWtzxyELjqri8CrPPJrRfJOtEVju4A%2FxvrNJFFMa60BARDvcrcVV3RKG4CpgfR6A%3D%3D HTTP/1.1" 200 1504
[13/Jan/2018 16:06:46] "GET /wx_in/?code=011fmWss1g6kWo09HSps15hZss1fmWs6&state=123&nsukey=H30p1V0dFRzfolPFOP7VUf689MIGgjPjs72j48HiAOJTocP%2BJDhiiAHdAXoAJkI4TqU0dF4yDR73%2FFyR3gfYv9LNjZvug2MJPdhyTL1C4HTvZ0ddgKPDh6JNn92FnA7nvPU87qBcdaamimiAEm%2FyCSSWtzxyELjqri8CrPPJrRfJOtEVju4A%2FxvrNJFFMa60BARDvcrcVV3RKG4CpgfR6A%3D%3D HTTP/1.1" 200 1480
[13/Jan/2018 16:06:46] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 16:06:46] "GET /static/js/index.js HTTP/1.1" 404 1759
[13/Jan/2018 16:06:48] "GET /wx_in/?code=011fmWss1g6kWo09HSps15hZss1fmWs6&state=123&nsukey=H30p1V0dFRzfolPFOP7VUf689MIGgjPjs72j48HiAOJTocP%2BJDhiiAHdAXoAJkI4TqU0dF4yDR73%2FFyR3gfYv9LNjZvug2MJPdhyTL1C4HTvZ0ddgKPDh6JNn92FnA7nvPU87qBcdaamimiAEm%2FyCSSWtzxyELjqri8CrPPJrRfJOtEVju4A%2FxvrNJFFMa60BARDvcrcVV3RKG4CpgfR6A%3D%3D HTTP/1.1" 200 1480
[13/Jan/2018 16:06:48] "GET /static/js/index.js HTTP/1.1" 404 1759
[13/Jan/2018 16:06:48] "GET /static/css/index.css HTTP/1.1" 404 1765
Not Found: /favicon.ico
[13/Jan/2018 16:06:48] "GET /favicon.ico HTTP/1.1" 404 2627
[13/Jan/2018 16:07:37] "GET /wx?nsukey=EJZeq%2BTL13jFWBXSUMQ2KD5ubKJyGdvIZUP%2BR0rVW0EDAzOX61Xnp2tTK%2BeYuSm92BetKcR92fc7doXrJIYOQ8XIgyNIeyz5sYkN3NLZeFuHb86rx0NjwvvdgDk3t2Q2h%2FEbXMv6Vly4r246ZX%2FBbM6akDD0AUXwnP1XhBVIK%2BBNuKJRByLKDBNRqdtvrCm0kjGBdwRn204wdf7miUqbzA%3D%3D HTTP/1.1" 301 0
[13/Jan/2018 16:07:39] "GET /wx/?nsukey=EJZeq%2BTL13jFWBXSUMQ2KD5ubKJyGdvIZUP%2BR0rVW0EDAzOX61Xnp2tTK%2BeYuSm92BetKcR92fc7doXrJIYOQ8XIgyNIeyz5sYkN3NLZeFuHb86rx0NjwvvdgDk3t2Q2h%2FEbXMv6Vly4r246ZX%2FBbM6akDD0AUXwnP1XhBVIK%2BBNuKJRByLKDBNRqdtvrCm0kjGBdwRn204wdf7miUqbzA%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 16:10:04] "GET /wx/?nsukey=EJZeq%2BTL13jFWBXSUMQ2KD5ubKJyGdvIZUP%2BR0rVW0EDAzOX61Xnp2tTK%2BeYuSm92BetKcR92fc7doXrJIYOQ8XIgyNIeyz5sYkN3NLZeFuHb86rx0NjwvvdgDk3t2Q2h%2FEbXMv6Vly4r246ZX%2FBbM6akDD0AUXwnP1XhBVIK%2BBNuKJRByLKDBNRqdtvrCm0kjGBdwRn204wdf7miUqbzA%3D%3D HTTP/1.1" 302 0
[13/Jan/2018 16:10:48] "GET /index/ HTTP/1.1" 200 1298
[13/Jan/2018 16:10:48] "GET /static/css/index.css HTTP/1.1" 404 1765
[13/Jan/2018 16:10:48] "GET /static/js/index.js HTTP/1.1" 404 1759
[13/Jan/2018 16:10:53] "GET /index/ HTTP/1.1" 200 1298
[13/Jan/2018 16:10:54] "GET /static/js/index.js HTTP/1.1" 404 1759
[13/Jan/2018 16:10:54] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:24:19] "GET /index_register_person/ HTTP/1.1" 200 4691
[24/Jan/2018 15:24:19] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:24:19] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:24:21] "GET /index_register_person/ HTTP/1.1" 200 4691
[24/Jan/2018 15:24:21] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:24:21] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:24:26] "GET /index_search_person/ HTTP/1.1" 200 1783
[24/Jan/2018 15:24:26] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:24:26] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:25:03] "GET /index_search_person/ HTTP/1.1" 200 1783
[24/Jan/2018 15:25:03] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:25:03] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:25:03] "GET /index_search_person/ HTTP/1.1" 200 1783
[24/Jan/2018 15:25:04] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:25:04] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:25:09] "GET /index_register_person/ HTTP/1.1" 200 4691
[24/Jan/2018 15:25:09] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:25:09] "GET /static/js/index.js HTTP/1.1" 404 1759
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[24/Jan/2018 15:36:01] "GET / HTTP/1.1" 500 80846
[24/Jan/2018 15:41:10] "GET /index_search_person/ HTTP/1.1" 200 1783
[24/Jan/2018 15:41:10] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:41:10] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:41:13] "POST /search_person/ HTTP/1.1" 200 1855
[24/Jan/2018 15:41:13] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:41:13] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:41:13] "GET /static/images/persons/qr_330900197506258701.png HTTP/1.1" 200 679
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[24/Jan/2018 15:47:07] "GET / HTTP/1.1" 500 80792
[24/Jan/2018 15:49:55] "GET /index_search_team/ HTTP/1.1" 200 1790
[24/Jan/2018 15:49:55] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:49:55] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:49:57] "POST /search_team/ HTTP/1.1" 200 1860
[24/Jan/2018 15:49:58] "GET /static/css/index.css HTTP/1.1" 404 1765
[24/Jan/2018 15:49:58] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:49:58] "GET /static/images/teams/qr_350124196612071664.png HTTP/1.1" 200 709
[24/Jan/2018 15:50:02] "POST /search_team/ HTTP/1.1" 200 1884
[24/Jan/2018 15:50:02] "GET /static/js/index.js HTTP/1.1" 404 1759
[24/Jan/2018 15:50:02] "GET /static/css/index.css HTTP/1.1" 404 1765
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[24/Jan/2018 16:23:51] "GET / HTTP/1.1" 500 80618
Not Found: /manager/html
[24/Jan/2018 16:35:01] "GET /manager/html HTTP/1.1" 404 3798
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[24/Jan/2018 16:56:21] "GET / HTTP/1.1" 500 80791
Invalid HTTP_HOST header: '111.230.224.59:8000'. You may need to add u'111.230.224.59' to ALLOWED_HOSTS.
[24/Jan/2018 17:41:39] "GET / HTTP/1.1" 400 60146
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[24/Jan/2018 17:41:39] "GET / HTTP/1.1" 500 59
[2018-01-24 17:41:39,287] - Broken pipe from ('114.215.45.101', 7176)

Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[24/Jan/2018 17:47:30] "GET / HTTP/1.1" 500 80852
[2018-01-24 17:47:30,317] - Broken pipe from ('60.191.38.78', 50096)

Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[24/Jan/2018 18:33:06] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 60794
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[24/Jan/2018 18:33:06] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 500 59
[2018-01-24 18:33:06,718] - Broken pipe from ('80.82.78.50', 55956)

Not Found: /manager/html
[24/Jan/2018 18:42:11] "GET /manager/html HTTP/1.1" 404 3798
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[24/Jan/2018 18:45:50] "GET / HTTP/1.1" 500 80619
Not Found: /index.action
[24/Jan/2018 18:45:50] "GET /index.action HTTP/1.1" 404 3798
Invalid HTTP_HOST header: 'localhost.localdomain'. You may need to add u'localhost.localdomain' to ALLOWED_HOSTS.
[24/Jan/2018 20:03:58] "HEAD /phpmyadmin/scripts/setup.php HTTP/1.0" 400 60464
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[24/Jan/2018 20:03:58] "HEAD /phpmyadmin/scripts/setup.php HTTP/1.0" 500 59
[2018-01-24 20:03:58,675] - Broken pipe from ('66.111.57.40', 44146)

Invalid HTTP_HOST header: 'localhost.localdomain'. You may need to add u'localhost.localdomain' to ALLOWED_HOSTS.
[24/Jan/2018 20:05:57] "GET /pma/scripts/setup.php HTTP/1.0" 400 60017
[24/Jan/2018 20:06:35] code 400, message Bad request version ('\xd9\xb5\x99?$\xee\xe8\x18\xd7C>C\xff[\xbc[`\xb3a\xa1\x08.\xf7\xd9\x19d\xfa\xf1h"\xbb\xb2\x11D\x06B\xefW\xb7\xb2t\xee\xc7M\xce\xa7\xf0l\xa3\xd8x\x1b\x8b%P')
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/site-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 1: ordinal not in range(128)
Logged from file basehttp.py, line 124
Not Found: /index.action
[24/Jan/2018 20:37:24] "GET /index.action HTTP/1.1" 404 3798
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[24/Jan/2018 20:57:17] "GET / HTTP/1.1" 500 81228
Not Found: /cgi/common.cgi
[24/Jan/2018 22:04:10] "GET /cgi/common.cgi HTTP/1.1" 404 3804
Not Found: /stssys.htm
[24/Jan/2018 22:04:11] "GET /stssys.htm HTTP/1.1" 404 3792
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[24/Jan/2018 22:04:12] "GET / HTTP/1.1" 500 80649
Not Found: /command.php
[24/Jan/2018 22:04:13] "POST /command.php HTTP/1.1" 404 3796
Invalid HTTP_HOST header: 'proxy.httpdaili.com'. You may need to add u'proxy.httpdaili.com' to ALLOWED_HOSTS.
[24/Jan/2018 23:13:38] "GET http://proxy.httpdaili.com/ip.asp?ip=111.231.93.28&dk=80 HTTP/1.1" 400 61112
Invalid HTTP_HOST header: 'localhost.localdomain'. You may need to add u'localhost.localdomain' to ALLOWED_HOSTS.
[25/Jan/2018 00:47:20] "HEAD /pma/scripts/setup.php HTTP/1.0" 400 60389
Invalid HTTP_HOST header: '111.230.15.240:8000'. You may need to add u'111.230.15.240' to ALLOWED_HOSTS.
[25/Jan/2018 01:44:32] "GET / HTTP/1.1" 400 60363
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[25/Jan/2018 01:44:32] "GET / HTTP/1.1" 500 59
[2018-01-25 01:44:32,161] - Broken pipe from ('114.215.45.101', 8026)

Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[25/Jan/2018 01:50:55] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 60565
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[25/Jan/2018 01:50:55] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 500 59
[2018-01-25 01:50:55,102] - Broken pipe from ('94.102.49.174', 60075)

Invalid HTTP_HOST header: 'localhost.localdomain'. You may need to add u'localhost.localdomain' to ALLOWED_HOSTS.
[25/Jan/2018 02:25:50] "GET / HTTP/1.0" 400 60139
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[25/Jan/2018 02:25:50] "GET / HTTP/1.0" 500 59
[2018-01-25 02:25:50,604] - Broken pipe from ('178.73.215.171', 50715)

Not Found: /muieblackcat
[25/Jan/2018 03:53:08] "GET /muieblackcat HTTP/1.1" 404 3798
Not Found: //phpmyadmin/scripts/setup.php
[25/Jan/2018 03:53:13] "GET //phpmyadmin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: //pma/scripts/setup.php
[25/Jan/2018 03:53:14] "GET //pma/scripts/setup.php HTTP/1.1" 404 3828
Not Found: //myadmin/scripts/setup.php
[25/Jan/2018 03:53:15] "GET //myadmin/scripts/setup.php HTTP/1.1" 404 3840
Not Found: //MyAdmin/scripts/setup.php
[25/Jan/2018 03:53:17] "GET //MyAdmin/scripts/setup.php HTTP/1.1" 404 3840
Not Found: //phpmyadmin/scripts/setup.php
[25/Jan/2018 03:53:39] "GET //phpmyadmin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: //pma/scripts/setup.php
[25/Jan/2018 03:53:40] "GET //pma/scripts/setup.php HTTP/1.1" 404 3828
Not Found: //myadmin/scripts/setup.php
[25/Jan/2018 03:53:40] "GET //myadmin/scripts/setup.php HTTP/1.1" 404 3840
Not Found: //MyAdmin/scripts/setup.php
[25/Jan/2018 03:54:34] "GET //MyAdmin/scripts/setup.php HTTP/1.1" 404 3840
Not Found: /muieblackcat
[25/Jan/2018 03:55:51] "GET /muieblackcat HTTP/1.1" 404 3798
Not Found: //pma/scripts/setup.php
[25/Jan/2018 03:55:58] "GET //pma/scripts/setup.php HTTP/1.1" 404 3828
Not Found: //myadmin/scripts/setup.php
[25/Jan/2018 03:55:59] "GET //myadmin/scripts/setup.php HTTP/1.1" 404 3840
Invalid HTTP_HOST header: '47.95.32.16'. You may need to add u'47.95.32.16' to ALLOWED_HOSTS.
[25/Jan/2018 04:36:01] "GET http://47.95.32.16/validate.php?step=0&n=discover&proto=http&ip=111.231.93.28&port=80&t=1516854961115&h=47.94.43.182&cip=&xff=&loc=1156110000 HTTP/1.1" 400 63336
Invalid HTTP_HOST header: 'hm.baidu.com'. You may need to add u'hm.baidu.com' to ALLOWED_HOSTS.
[25/Jan/2018 06:02:03] "GET http://hm.baidu.com/hm.gif HTTP/1.1" 400 60294
Not Found: /manager/html
[25/Jan/2018 06:15:35] "GET /manager/html HTTP/1.1" 404 3801
Not Found: /favicon.ico
[25/Jan/2018 06:59:47] "GET /favicon.ico HTTP/1.1" 404 3795
Not Found: /favicon.ico
[25/Jan/2018 07:05:06] "GET /favicon.ico HTTP/1.1" 404 3795
Not Found: /favicon.ico
[25/Jan/2018 07:16:07] "GET /favicon.ico HTTP/1.1" 404 3795
[25/Jan/2018 07:16:08] "GET /index_register_person/ HTTP/1.1" 200 4691
[25/Jan/2018 07:16:09] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 07:16:09] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:16:31] "POST /register_person/ HTTP/1.1" 200 4704
[25/Jan/2018 07:16:31] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:16:31] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 07:18:26] "GET /index_search_person/ HTTP/1.1" 200 1783
[25/Jan/2018 07:18:26] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 07:18:26] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:18:36] "POST /search_person/ HTTP/1.1" 200 1855
[25/Jan/2018 07:18:37] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:18:37] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 07:18:37] "GET /static/images/persons/qr_111111111111111111.png HTTP/1.1" 200 717
[25/Jan/2018 07:18:58] "GET /index_register_team/ HTTP/1.1" 200 5093
[25/Jan/2018 07:18:58] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:18:58] "GET /static/js/index.js HTTP/1.1" 404 1759
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 170, in register_team
    ret = rg.register_team(card_id, year+"-"+month+"-"+day,people_number)
  File "/home/ticket/yuhuatai/piaowu/register/register.py", line 29, in register_team
    team = YuhuataiTeam.objects.create(card_id=card_id, visit_date=visit_date, people_number=people_number, user_uuid=uuid.uuid1())
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 393, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 1051, in as_sql
    for obj in self.query.objs
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 990, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 766, in get_db_prep_save
    prepared=False)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 1297, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 1292, in get_prep_value
    return self.to_python(value)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 1267, in to_python
    params={'value': value},
ValidationError: [u"'2018-02-' value has an invalid date format. It must be in YYYY-MM-DD format."]
[25/Jan/2018 07:20:11] "POST /register_team/ HTTP/1.1" 500 142818
[25/Jan/2018 07:20:13] "GET /index_register_team/ HTTP/1.1" 200 5093
[25/Jan/2018 07:20:13] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:20:13] "GET /static/js/index.js HTTP/1.1" 404 1759
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 170, in register_team
    ret = rg.register_team(card_id, year+"-"+month+"-"+day,people_number)
  File "/home/ticket/yuhuatai/piaowu/register/register.py", line 29, in register_team
    team = YuhuataiTeam.objects.create(card_id=card_id, visit_date=visit_date, people_number=people_number, user_uuid=uuid.uuid1())
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 393, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 1051, in as_sql
    for obj in self.query.objs
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 990, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 766, in get_db_prep_save
    prepared=False)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 1297, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 1292, in get_prep_value
    return self.to_python(value)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 1267, in to_python
    params={'value': value},
ValidationError: [u"'2018-02-' value has an invalid date format. It must be in YYYY-MM-DD format."]
[25/Jan/2018 07:20:32] "POST /register_team/ HTTP/1.1" 500 142813
[25/Jan/2018 07:20:34] "GET /index_register_team/ HTTP/1.1" 200 5093
[25/Jan/2018 07:20:34] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:20:34] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 07:20:48] "POST /register_team/ HTTP/1.1" 200 5106
[25/Jan/2018 07:20:48] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:20:48] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 07:21:11] "GET /index_search_team/ HTTP/1.1" 200 1790
[25/Jan/2018 07:21:12] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:21:12] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 07:21:24] "POST /search_team/ HTTP/1.1" 200 1884
[25/Jan/2018 07:21:24] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:21:24] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 07:21:33] "POST /search_team/ HTTP/1.1" 200 1860
[25/Jan/2018 07:21:33] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:21:33] "GET /static/images/teams/qr_111111111111111112.png HTTP/1.1" 200 666
[25/Jan/2018 07:21:33] "GET /static/js/index.js HTTP/1.1" 404 1759
Invalid HTTP_HOST header: 'localhost.localdomain'. You may need to add u'localhost.localdomain' to ALLOWED_HOSTS.
[25/Jan/2018 07:29:55] "GET / HTTP/1.0" 400 60139
[25/Jan/2018 07:52:19] "POST /register_person/ HTTP/1.1" 200 4704
[25/Jan/2018 07:52:19] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:52:19] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 07:57:05] "POST /register_person/ HTTP/1.1" 200 4704
[25/Jan/2018 07:57:05] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 07:57:05] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:10:22] "POST /search_person/ HTTP/1.1" 200 1855
[25/Jan/2018 08:10:22] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 08:10:22] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:10:22] "GET /static/images/persons/qr_111111111111111111.png HTTP/1.1" 200 647
[25/Jan/2018 08:12:28] "POST /search_person/ HTTP/1.1" 200 1879
[25/Jan/2018 08:12:28] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 08:12:28] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:15:33] "POST /register_team/ HTTP/1.1" 200 5106
[25/Jan/2018 08:15:33] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 08:15:33] "GET /static/js/index.js HTTP/1.1" 404 1759
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 170, in register_team
    ret = rg.register_team(card_id, year+"-"+month+"-"+day,people_number)
  File "/home/ticket/yuhuatai/piaowu/register/register.py", line 29, in register_team
    team = YuhuataiTeam.objects.create(card_id=card_id, visit_date=visit_date, people_number=people_number, user_uuid=uuid.uuid1())
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 393, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 1051, in as_sql
    for obj in self.query.objs
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 990, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 766, in get_db_prep_save
    prepared=False)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 758, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 1849, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[25/Jan/2018 08:16:09] "POST /register_team/ HTTP/1.1" 500 138335
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.handle()
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/site-packages/django/core/servers/basehttp.py", line 140, in handle
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/site-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 161, in register_team
    card_id = request.POST['card_id']
  File "/usr/lib64/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'card_id'"
[25/Jan/2018 08:16:48] "GET /register_team/ HTTP/1.1" 500 67881
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 161, in register_team
    card_id = request.POST['card_id']
  File "/usr/lib64/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'card_id'"
[25/Jan/2018 08:16:55] "GET /register_team/ HTTP/1.1" 500 67881
[25/Jan/2018 08:17:03] "POST /search_person/ HTTP/1.1" 200 1879
[25/Jan/2018 08:17:03] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 08:17:03] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:17:52] "POST /register_person/ HTTP/1.1" 200 4704
[25/Jan/2018 08:17:52] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:17:52] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 08:17:57] "POST /search_person/ HTTP/1.1" 200 1855
[25/Jan/2018 08:17:57] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 08:17:57] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:17:57] "GET /static/images/persons/qr_620921199910223586.png HTTP/1.1" 200 701
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 161, in register_team
    card_id = request.POST['card_id']
  File "/usr/lib64/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'card_id'"
[25/Jan/2018 08:18:02] "GET /register_team/ HTTP/1.1" 500 67881
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 161, in register_team
    card_id = request.POST['card_id']
  File "/usr/lib64/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'card_id'"
[25/Jan/2018 08:18:07] "GET /register_team/ HTTP/1.1" 500 67881
Not Found: /favicon.ico
[25/Jan/2018 08:18:26] "GET /favicon.ico HTTP/1.1" 404 3795
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 161, in register_team
    card_id = request.POST['card_id']
  File "/usr/lib64/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'card_id'"
[25/Jan/2018 08:18:28] "GET /register_team/ HTTP/1.1" 500 67156
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[25/Jan/2018 08:22:08] "GET /index_register_team/?nsukey=opYZOULqEwoDdFWFcKHYl9LKqblyOsaGNGShSE6NZHvpjyOSMXAxOLA8ACjJ7tpbXm2i0RW4o2nW5K1F1pZ2NbXd9Q688pi%2FIhVaCx4UGDHgE4XSrs5XXNqKjavrHWLiXoe9YrbvzYw57eqy4ntfKJiwntkzCX8Gc0aoiPZeUvFJZYUuyl%2BgmHKLQfwClpYTBTU3TkxLWy0NUyCSkih%2FXg%3D%3D HTTP/1.1" 200 5093
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[25/Jan/2018 08:22:08] "GET /index_register_team/?nsukey=opYZOULqEwoDdFWFcKHYl9LKqblyOsaGNGShSE6NZHvpjyOSMXAxOLA8ACjJ7tpbXm2i0RW4o2nW5K1F1pZ2NbXd9Q688pi%2FIhVaCx4UGDHgE4XSrs5XXNqKjavrHWLiXoe9YrbvzYw57eqy4ntfKJiwntkzCX8Gc0aoiPZeUvFJZYUuyl%2BgmHKLQfwClpYTBTU3TkxLWy0NUyCSkih%2FXg%3D%3D HTTP/1.1" 200 5093
[25/Jan/2018 08:22:08] "GET / HTTP/1.1" 500 81433
[25/Jan/2018 08:22:08] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:22:08] "GET / HTTP/1.1" 500 81434
[25/Jan/2018 08:22:08] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 08:22:08] "GET /index_register_team/?nsukey=opYZOULqEwoDdFWFcKHYl9LKqblyOsaGNGShSE6NZHvpjyOSMXAxOLA8ACjJ7tpbXm2i0RW4o2nW5K1F1pZ2NbXd9Q688pi%2FIhVaCx4UGDHgE4XSrs5XXNqKjavrHWLiXoe9YrbvzYw57eqy4ntfKJiwntkzCX8Gc0aoiPZeUvFJZYUuyl%2BgmHKLQfwClpYTBTU3TkxLWy0NUyCSkih%2FXg%3D%3D HTTP/1.1" 200 5093
[25/Jan/2018 08:22:09] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:22:09] "GET /static/css/index.css HTTP/1.1" 404 1765
Not Found: /favicon.ico
[25/Jan/2018 08:22:09] "GET /favicon.ico HTTP/1.1" 404 3795
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 161, in register_team
    card_id = request.POST['card_id']
  File "/usr/lib64/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'card_id'"
[25/Jan/2018 08:22:18] "GET /register_team/ HTTP/1.1" 500 67881
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 161, in register_team
    card_id = request.POST['card_id']
  File "/usr/lib64/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'card_id'"
[25/Jan/2018 08:22:19] "GET /register_team/ HTTP/1.1" 500 67881
Not Found: /favicon.ico
[25/Jan/2018 08:22:41] "GET /favicon.ico HTTP/1.1" 404 3795
Internal Server Error: /register_team/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 161, in register_team
    card_id = request.POST['card_id']
  File "/usr/lib64/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'card_id'"
[25/Jan/2018 08:22:43] "GET /register_team/ HTTP/1.1" 500 67156
[25/Jan/2018 08:23:02] "GET /index_register_team HTTP/1.1" 301 0
[25/Jan/2018 08:23:06] "POST /search_team/ HTTP/1.1" 200 1860
[25/Jan/2018 08:23:06] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 08:23:06] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:23:06] "GET /static/images/teams/qr_111111111111111112.png HTTP/1.1" 200 666
[25/Jan/2018 08:23:07] "GET /index_register_team/?nsukey=opYZOULqEwoDdFWFcKHYl9LKqblyOsaGNGShSE6NZHvpjyOSMXAxOLA8ACjJ7tpbXm2i0RW4o2nW5K1F1pZ2NbXd9Q688pi%2FIhVaCx4UGDHgE4XSrs5XXNqKjavrHWLiXoe9YrbvzYw57eqy4ntfKJiwntkzCX8Gc0aoiPZeUvFJZYUuyl%2BgmHKLQfwClpYTBTU3TkxLWy0NUyCSkih%2FXg%3D%3D HTTP/1.1" 200 5093
[25/Jan/2018 08:23:07] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:23:12] "POST /search_team/ HTTP/1.1" 200 1884
[25/Jan/2018 08:23:12] "GET /static/css/index.css HTTP/1.1" 404 1765
[25/Jan/2018 08:23:12] "GET /static/js/index.js HTTP/1.1" 404 1759
[25/Jan/2018 08:25:29] "GET /index_register_team HTTP/1.1" 301 0
[25/Jan/2018 08:25:29] "GET /index_register_team/ HTTP/1.1" 200 5093
[25/Jan/2018 08:25:30] "GET /static/js/index.js HTTP/1.1" 404 1759
Invalid HTTP_HOST header: '-c'. You may need to add u'-c' to ALLOWED_HOSTS.
[25/Jan/2018 08:29:46] "POST //%63%67%69%2D%62%69%6E/%70%68%70?%2D%64+%61%6C%6C%6F%77%5F%75%72%6C%5F%69%6E%63%6C%75%64%65%3D%6F%6E+%2D%64+%73%61%66%65%5F%6D%6F%64%65%3D%6F%66%66+%2D%64+%73%75%68%6F%73%69%6E%2E%73%69%6D%75%6C%61%74%69%6F%6E%3D%6F%6E+%2D%64+%64%69%73%61%62%6C%65%5F%66%75%6E%63%74%69%6F%6E%73%3D%22%22+%2D%64+%6F%70%65%6E%5F%62%61%73%65%64%69%72%3D%6E%6F%6E%65+%2D%64+%61%75%74%6F%5F%70%72%65%70%65%6E%64%5F%66%69%6C%65%3D%70%68%70%3A%2F%2F%69%6E%70%75%74+%2D%64+%63%67%69%2E%66%6F%72%63%65%5F%72%65%64%69%72%65%63%74%3D%30+%2D%64+%63%67%69%2E%72%65%64%69%72%65%63%74%5F%73%74%61%74%75%73%5F%65%6E%76%3D%30+%2D%64+%61%75%74%6F%5F%70%72%65%70%65%6E%64%5F%66%69%6C%65%3D%70%68%70%3A%2F%2F%69%6E%70%75%74+%2D%6E HTTP/1.1" 400 66453
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/site-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/site-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/site-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/site-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Invalid HTTP_HOST header: '115.159.31.128:8000'. You may need to add u'115.159.31.128' to ALLOWED_HOSTS.
[25/Jan/2018 09:45:00] "GET / HTTP/1.1" 400 60361
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[25/Jan/2018 09:45:00] "GET / HTTP/1.1" 500 59
[2018-01-25 09:45:00,089] - Broken pipe from ('59.110.6.177', 20983)

Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[25/Jan/2018 13:23:36] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 60797
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[25/Jan/2018 13:23:36] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 500 59
[2018-01-25 13:23:36,163] - Broken pipe from ('172.82.166.210', 55130)

Not Found: /phpmyadmin
[25/Jan/2018 13:39:00] "GET /phpmyadmin HTTP/1.1" 404 3792
Not Found: /phpmyadmin
[25/Jan/2018 15:45:03] "GET /phpmyadmin HTTP/1.1" 404 3792
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[25/Jan/2018 17:15:18] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 60794
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[25/Jan/2018 17:15:18] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 500 59
[2018-01-25 17:15:18,583] - Broken pipe from ('80.82.78.50', 59077)

Invalid HTTP_HOST header: '58.87.71.152:8000'. You may need to add u'58.87.71.152' to ALLOWED_HOSTS.
[25/Jan/2018 17:51:22] "GET / HTTP/1.1" 400 60333
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[25/Jan/2018 17:51:22] "GET / HTTP/1.1" 500 59
[2018-01-25 17:51:22,841] - Broken pipe from ('116.62.176.205', 21814)

Invalid HTTP_HOST header: 'www.qq.com'. You may need to add u'www.qq.com' to ALLOWED_HOSTS.
[25/Jan/2018 20:24:07] "GET http://www.qq.com/404/search_children.js HTTP/1.1" 400 60894
[2018-01-25 20:24:07,065] - Broken pipe from ('120.132.3.65', 54054)

[25/Jan/2018 20:24:11] code 400, message Bad request syntax ('\x04\x01\x00PpTi4\x00')
[25/Jan/2018 20:24:11] " PpTi4 " 400 -
[25/Jan/2018 20:24:11] code 400, message Bad request syntax ('\x05\x01\x00')
[25/Jan/2018 20:24:11] " " 400 -
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[25/Jan/2018 22:36:47] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 60796
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[25/Jan/2018 22:36:47] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 500 59
[2018-01-25 22:36:47,341] - Broken pipe from ('94.102.49.174', 51996)

Not Found: /favicon.ico
[26/Jan/2018 00:52:54] "GET /favicon.ico HTTP/1.1" 404 3795
Invalid HTTP_HOST header: 'wwww'. You may need to add u'wwww' to ALLOWED_HOSTS.
[26/Jan/2018 01:01:17] "HEAD /phpmyadmin/scripts/setup.php HTTP/1.1" 400 60475
Not Found: /muieblackcat
[26/Jan/2018 01:19:06] "GET /muieblackcat HTTP/1.1" 404 3798
Not Found: //phpMyAdmin/scripts/setup.php
[26/Jan/2018 01:19:07] "GET //phpMyAdmin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: //phpmyadmin/scripts/setup.php
[26/Jan/2018 01:19:08] "GET //phpmyadmin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: //pma/scripts/setup.php
[26/Jan/2018 01:19:08] "GET //pma/scripts/setup.php HTTP/1.1" 404 3828
Not Found: //myadmin/scripts/setup.php
[26/Jan/2018 01:19:09] "GET //myadmin/scripts/setup.php HTTP/1.1" 404 3840
Not Found: //MyAdmin/scripts/setup.php
[26/Jan/2018 01:19:10] "GET //MyAdmin/scripts/setup.php HTTP/1.1" 404 3840
Invalid HTTP_HOST header: 'proxy.httpdaili.com'. You may need to add u'proxy.httpdaili.com' to ALLOWED_HOSTS.
[26/Jan/2018 01:19:28] "GET http://proxy.httpdaili.com/ip.asp?ip=111.231.93.28&dk=80 HTTP/1.1" 400 61343
Invalid HTTP_HOST header: '111.230.195.28:8000'. You may need to add u'111.230.195.28' to ALLOWED_HOSTS.
[26/Jan/2018 01:42:20] "GET / HTTP/1.1" 400 60362
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[26/Jan/2018 01:42:20] "GET / HTTP/1.1" 500 59
[2018-01-26 01:42:20,365] - Broken pipe from ('114.215.45.79', 25427)

Not Found: //phpMyAdmin/scripts/setup.php
[26/Jan/2018 04:13:10] "GET //phpMyAdmin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /muieblackcat
[26/Jan/2018 04:17:01] "GET /muieblackcat HTTP/1.1" 404 3798
Not Found: /w00tw00t.at.blackhats.romanian.anti-sec:)
[26/Jan/2018 05:14:13] "GET /w00tw00t.at.blackhats.romanian.anti-sec:) HTTP/1.1" 404 3885
Not Found: /MyAdmin/scripts/setup.php
[26/Jan/2018 05:14:14] "GET /MyAdmin/scripts/setup.php HTTP/1.1" 404 3837
Not Found: /PMA/scripts/setup.php
[26/Jan/2018 05:14:16] "GET /PMA/scripts/setup.php HTTP/1.1" 404 3825
Not Found: /admin/mysql/scripts/setup.php
[26/Jan/2018 05:14:16] "GET /admin/mysql/scripts/setup.php HTTP/1.1" 404 6144
Not Found: /admin/phpmyadmin/scripts/setup.php
[26/Jan/2018 05:14:20] "GET /admin/phpmyadmin/scripts/setup.php HTTP/1.1" 404 6159
Not Found: /admin/pma/scripts/setup.php
[26/Jan/2018 05:14:38] "GET /admin/pma/scripts/setup.php HTTP/1.1" 404 6138
Not Found: /admin/scripts/setup.php
[26/Jan/2018 05:14:39] "GET /admin/scripts/setup.php HTTP/1.1" 404 6126
Not Found: /admin/setup.php
[26/Jan/2018 05:14:40] "GET /admin/setup.php HTTP/1.1" 404 6102
Not Found: /admin/sql/scripts/setup.php
[26/Jan/2018 05:14:44] "GET /admin/sql/scripts/setup.php HTTP/1.1" 404 6138
Not Found: /blog/phpmyadmin/scripts/setup.php
[26/Jan/2018 05:14:45] "GET /blog/phpmyadmin/scripts/setup.php HTTP/1.1" 404 3861
Not Found: /cpadmin/scripts/setup.php
[26/Jan/2018 05:14:45] "GET /cpadmin/scripts/setup.php HTTP/1.1" 404 3837
Not Found: /cpadmindb/scripts/setup.php
[26/Jan/2018 05:14:46] "GET /cpadmindb/scripts/setup.php HTTP/1.1" 404 3843
Not Found: /cpanelmysql/scripts/setup.php
[26/Jan/2018 05:14:47] "GET /cpanelmysql/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /cpanelphpmyadmin/scripts/setup.php
[26/Jan/2018 05:14:49] "GET /cpanelphpmyadmin/scripts/setup.php HTTP/1.1" 404 3864
Not Found: /database/scripts/setup.php
[26/Jan/2018 05:14:50] "GET /database/scripts/setup.php HTTP/1.1" 404 3840
Not Found: /db/scripts/setup.php
[26/Jan/2018 05:14:51] "GET /db/scripts/setup.php HTTP/1.1" 404 3822
Not Found: /dbadmin/scripts/setup.php
[26/Jan/2018 05:14:51] "GET /dbadmin/scripts/setup.php HTTP/1.1" 404 3837
Not Found: /my/scripts/setup.php
[26/Jan/2018 05:14:53] "GET /my/scripts/setup.php HTTP/1.1" 404 3822
Not Found: /myAdmin/scripts/setup.php
[26/Jan/2018 05:14:54] "GET /myAdmin/scripts/setup.php HTTP/1.1" 404 3837
Not Found: /myadmin/scripts/setup.php
[26/Jan/2018 05:14:55] "GET /myadmin/scripts/setup.php HTTP/1.1" 404 3837
Not Found: /mysql-admin/scripts/setup.php
[26/Jan/2018 05:14:56] "GET /mysql-admin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /mysql/scripts/setup.php
[26/Jan/2018 05:14:57] "GET /mysql/scripts/setup.php HTTP/1.1" 404 3831
Not Found: /mysqladmin/scripts/setup.php
[26/Jan/2018 05:14:58] "GET /mysqladmin/scripts/setup.php HTTP/1.1" 404 3846
Not Found: /mysqlmanager/scripts/setup.php
[26/Jan/2018 05:15:00] "GET /mysqlmanager/scripts/setup.php HTTP/1.1" 404 3852
Not Found: /p/m/a/scripts/setup.php
[26/Jan/2018 05:15:00] "GET /p/m/a/scripts/setup.php HTTP/1.1" 404 3831
Not Found: /php-myadmin/scripts/setup.php
[26/Jan/2018 05:15:01] "GET /php-myadmin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /php/phpmyadmin/scripts/setup.php
[26/Jan/2018 05:15:02] "GET /php/phpmyadmin/scripts/setup.php HTTP/1.1" 404 3858
Not Found: /phpMyAdmin-2.10.0.0/scripts/setup.php
[26/Jan/2018 05:15:03] "GET /phpMyAdmin-2.10.0.0/scripts/setup.php HTTP/1.1" 404 3873
Not Found: /phpMyAdmin-2.10.0/scripts/setup.php
[26/Jan/2018 05:15:05] "GET /phpMyAdmin-2.10.0/scripts/setup.php HTTP/1.1" 404 3867
Not Found: /phpMyAdmin-2.11.11.3/scripts/setup.php
[26/Jan/2018 05:15:06] "GET /phpMyAdmin-2.11.11.3/scripts/setup.php HTTP/1.1" 404 3876
Not Found: /phpMyAdmin-2.11.11/scripts/setup.php
[26/Jan/2018 05:15:07] "GET /phpMyAdmin-2.11.11/scripts/setup.php HTTP/1.1" 404 3870
Not Found: /phpMyAdmin-2.5.5/index.php
[26/Jan/2018 05:15:08] "GET /phpMyAdmin-2.5.5/index.php HTTP/1.1" 404 3840
Not Found: /phpMyAdmin/scripts/setup.php
[26/Jan/2018 05:15:09] "GET /phpMyAdmin/scripts/setup.php HTTP/1.1" 404 3846
Not Found: /phpMyAdmin2/scripts/setup.php
[26/Jan/2018 05:15:10] "GET /phpMyAdmin2/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /phpadmin/scripts/setup.php
[26/Jan/2018 05:15:12] "GET /phpadmin/scripts/setup.php HTTP/1.1" 404 3840
Not Found: /phpmanager/scripts/setup.php
[26/Jan/2018 05:15:14] "GET /phpmanager/scripts/setup.php HTTP/1.1" 404 3846
Not Found: /phpmy-admin/scripts/setup.php
[26/Jan/2018 05:15:16] "GET /phpmy-admin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /phpmyadmin/scripts/setup.php
[26/Jan/2018 05:15:17] "GET /phpmyadmin/scripts/setup.php HTTP/1.1" 404 3846
Not Found: /pma/scripts/setup.php
[26/Jan/2018 05:15:36] "GET /pma/scripts/setup.php HTTP/1.1" 404 3825
Not Found: /scripts/setup.php
[26/Jan/2018 05:15:37] "GET /scripts/setup.php HTTP/1.1" 404 3813
Not Found: /setup.php
[26/Jan/2018 05:15:37] "GET /setup.php HTTP/1.1" 404 3789
Not Found: /sqladm/scripts/setup.php
[26/Jan/2018 05:15:38] "GET /sqladm/scripts/setup.php HTTP/1.1" 404 3834
Not Found: /sqladmin/scripts/setup.php
[26/Jan/2018 05:15:39] "GET /sqladmin/scripts/setup.php HTTP/1.1" 404 3840
Not Found: /web/phpmyadmin/scripts/setup.php
[26/Jan/2018 05:15:39] "GET /web/phpmyadmin/scripts/setup.php HTTP/1.1" 404 3858
Not Found: /web/scripts/setup.php
[26/Jan/2018 05:15:40] "GET /web/scripts/setup.php HTTP/1.1" 404 3825
Not Found: /webadmin/scripts/setup.php
[26/Jan/2018 05:15:41] "GET /webadmin/scripts/setup.php HTTP/1.1" 404 3840
Not Found: /webdb/scripts/setup.php
[26/Jan/2018 05:15:42] "GET /webdb/scripts/setup.php HTTP/1.1" 404 3831
Not Found: /websql/scripts/setup.php
[26/Jan/2018 05:15:43] "GET /websql/scripts/setup.php HTTP/1.1" 404 3834
Not Found: /xampp/phpmyadmin/scripts/setup.php
[26/Jan/2018 05:15:43] "GET /xampp/phpmyadmin/scripts/setup.php HTTP/1.1" 404 3864
Not Found: /w00tw00t.at.blackhats.romanian.anti-sec:)
[26/Jan/2018 05:35:17] "GET /w00tw00t.at.blackhats.romanian.anti-sec:) HTTP/1.1" 404 3885
Not Found: /phpMyAdmin/scripts/setup.php
[26/Jan/2018 05:35:18] "GET /phpMyAdmin/scripts/setup.php HTTP/1.1" 404 3846
Not Found: /phpmyadmin/scripts/setup.php
[26/Jan/2018 05:35:18] "GET /phpmyadmin/scripts/setup.php HTTP/1.1" 404 3846
Not Found: /pma/scripts/setup.php
[26/Jan/2018 05:35:19] "GET /pma/scripts/setup.php HTTP/1.1" 404 3825
Not Found: /myadmin/scripts/setup.php
[26/Jan/2018 05:35:20] "GET /myadmin/scripts/setup.php HTTP/1.1" 404 3837
Not Found: /MyAdmin/scripts/setup.php
[26/Jan/2018 05:35:20] "GET /MyAdmin/scripts/setup.php HTTP/1.1" 404 3837
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[26/Jan/2018 06:58:18] "GET / HTTP/1.1" 500 81083
[2018-01-26 06:58:18,171] - Broken pipe from ('60.191.38.78', 15483)

Not Found: /pma/scripts/setup.php
[26/Jan/2018 07:28:18] "GET /pma/scripts/setup.php HTTP/1.1" 404 3825
Not Found: /setup.php
[26/Jan/2018 07:36:03] "GET /setup.php HTTP/1.1" 404 3789
Not Found: /phpmy-admin/scripts/setup.php
[26/Jan/2018 07:44:27] "GET /phpmy-admin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /w00tw00t.at.blackhats.romanian.anti-sec:)
[26/Jan/2018 07:49:06] "GET /w00tw00t.at.blackhats.romanian.anti-sec:) HTTP/1.1" 404 3885
Not Found: /myAdmin/scripts/setup.php
[26/Jan/2018 07:50:06] "GET /myAdmin/scripts/setup.php HTTP/1.1" 404 3837
Not Found: /phpMyAdmin2/scripts/setup.php
[26/Jan/2018 07:56:22] "GET /phpMyAdmin2/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /phpadmin/scripts/setup.php
[26/Jan/2018 07:56:22] "GET /phpadmin/scripts/setup.php HTTP/1.1" 404 3840
Not Found: /phpMyAdmin/scripts/setup.php
[26/Jan/2018 08:03:18] "GET /phpMyAdmin/scripts/setup.php HTTP/1.1" 404 3846
Not Found: /mysql-admin/scripts/setup.php
[26/Jan/2018 08:05:01] "GET /mysql-admin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /php-myadmin/scripts/setup.php
[26/Jan/2018 08:05:56] "GET /php-myadmin/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /database/scripts/setup.php
[26/Jan/2018 08:09:24] "GET /database/scripts/setup.php HTTP/1.1" 404 3840
Not Found: /phpMyAdmin-2.5.5/index.php
[26/Jan/2018 08:14:49] "GET /phpMyAdmin-2.5.5/index.php HTTP/1.1" 404 3840
Not Found: /blog/phpmyadmin/scripts/setup.php
Not Found: /web/scripts/setup.php
[26/Jan/2018 08:20:35] "GET /blog/phpmyadmin/scripts/setup.php HTTP/1.1" 404 3861
[26/Jan/2018 08:20:35] "GET /web/scripts/setup.php HTTP/1.1" 404 3825
Not Found: /pmd/index.php
[26/Jan/2018 08:24:14] "HEAD /pmd/index.php HTTP/1.1" 404 3802
Not Found: /ccvv
[26/Jan/2018 09:18:34] "GET /ccvv HTTP/1.1" 404 3774
Not Found: /mysqlmanager/scripts/setup.php
[26/Jan/2018 09:18:57] "GET /mysqlmanager/scripts/setup.php HTTP/1.1" 404 3852
Invalid HTTP_HOST header: '111.230.1.144:8000'. You may need to add u'111.230.1.144' to ALLOWED_HOSTS.
[26/Jan/2018 09:43:55] "GET / HTTP/1.1" 400 60347
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[26/Jan/2018 09:43:55] "GET / HTTP/1.1" 500 59
[2018-01-26 09:43:55,670] - Broken pipe from ('114.215.45.79', 23984)

Not Found: /manager/html
[26/Jan/2018 09:59:35] "GET /manager/html HTTP/1.1" 404 3801
Not Found: /pmd/index.php
[26/Jan/2018 10:47:17] "GET /pmd/index.php HTTP/1.1" 404 3801
Invalid HTTP_HOST header: '-c'. You may need to add u'-c' to ALLOWED_HOSTS.
[26/Jan/2018 10:55:27] "POST //%63%67%69%2D%62%69%6E/%70%68%70?%2D%64+%61%6C%6C%6F%77%5F%75%72%6C%5F%69%6E%63%6C%75%64%65%3D%6F%6E+%2D%64+%73%61%66%65%5F%6D%6F%64%65%3D%6F%66%66+%2D%64+%73%75%68%6F%73%69%6E%2E%73%69%6D%75%6C%61%74%69%6F%6E%3D%6F%6E+%2D%64+%64%69%73%61%62%6C%65%5F%66%75%6E%63%74%69%6F%6E%73%3D%22%22+%2D%64+%6F%70%65%6E%5F%62%61%73%65%64%69%72%3D%6E%6F%6E%65+%2D%64+%61%75%74%6F%5F%70%72%65%70%65%6E%64%5F%66%69%6C%65%3D%70%68%70%3A%2F%2F%69%6E%70%75%74+%2D%64+%63%67%69%2E%66%6F%72%63%65%5F%72%65%64%69%72%65%63%74%3D%30+%2D%64+%63%67%69%2E%72%65%64%69%72%65%63%74%5F%73%74%61%74%75%73%5F%65%6E%76%3D%30+%2D%64+%61%75%74%6F%5F%70%72%65%70%65%6E%64%5F%66%69%6C%65%3D%70%68%70%3A%2F%2F%69%6E%70%75%74+%2D%6E HTTP/1.1" 400 67256
Invalid HTTP_HOST header: 'localhost.localdomain'. You may need to add u'localhost.localdomain' to ALLOWED_HOSTS.
[26/Jan/2018 11:08:23] "GET / HTTP/1.0" 400 60319
Not Found: /ccvv
[26/Jan/2018 11:46:55] "GET /ccvv HTTP/1.1" 404 3774
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[26/Jan/2018 12:17:58] "GET / HTTP/1.1" 500 81230
[26/Jan/2018 12:23:56] code 400, message Bad request syntax ('\x03\x00\x00\x13\x0e\xe0\x00\x00\x00\x00\x00\x01\x00\x08\x00\x00\x00\x00\x00')
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/site-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
Logged from file basehttp.py, line 124
[26/Jan/2018 12:34:11] "GET /index_search_person/ HTTP/1.1" 200 1783
[26/Jan/2018 12:34:11] "GET /static/js/index.js HTTP/1.1" 404 1759
[26/Jan/2018 12:34:11] "GET /static/css/index.css HTTP/1.1" 404 1765
Invalid HTTP_HOST header: 'localhost.localdomain'. You may need to add u'localhost.localdomain' to ALLOWED_HOSTS.
[26/Jan/2018 13:32:10] "GET / HTTP/1.0" 400 60015
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[26/Jan/2018 14:07:25] "GET / HTTP/1.1" 500 80849
Invalid HTTP_HOST header: 'wap.ip138.com'. You may need to add u'wap.ip138.com' to ALLOWED_HOSTS.
[26/Jan/2018 14:19:59] "HEAD http://wap.ip138.com/ HTTP/1.1" 400 60707
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[26/Jan/2018 14:19:59] "HEAD http://wap.ip138.com/ HTTP/1.1" 500 59
[2018-01-26 14:19:59,932] - Broken pipe from ('60.191.52.254', 43653)

[26/Jan/2018 14:20:26] code 400, message Bad request syntax ('\x05\x02\x00\x02')
[26/Jan/2018 14:20:26] " " 400 -
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib64/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 58, in get_response
    return debug.technical_404_response(request, e)
  File "/usr/lib64/python2.7/site-packages/django/views/debug.py", line 513, in technical_404_response
    return HttpResponseNotFound(t.render(c), content_type='text/html')
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 708, in resolve
    obj = self.var.resolve(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 849, in resolve
    value = self._resolve_lookup(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 911, in _resolve_lookup
    current = current()
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 183, in build_absolute_uri
    host=self.get_host(),
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 113, in get_host
    raise DisallowedHost(msg)
DisallowedHost: Invalid HTTP_HOST header: 'www.w5188.com'. You may need to add u'www.w5188.com' to ALLOWED_HOSTS.
[26/Jan/2018 14:40:40] "HEAD /static/mango/img/lllooo.png HTTP/1.1" 500 59
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[26/Jan/2018 15:04:42] "GET / HTTP/1.1" 500 81230
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[26/Jan/2018 16:06:37] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 60794
Not Found: /phpMyAdmin2/scripts/setup.php
[26/Jan/2018 17:19:31] "GET /phpMyAdmin2/scripts/setup.php HTTP/1.1" 404 3849
Not Found: /phpadmin/scripts/setup.php
[26/Jan/2018 17:19:31] "GET /phpadmin/scripts/setup.php HTTP/1.1" 404 3840
Invalid HTTP_HOST header: '111.230.139.56:8000'. You may need to add u'111.230.139.56' to ALLOWED_HOSTS.
[26/Jan/2018 17:43:45] "GET / HTTP/1.1" 400 60363
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[26/Jan/2018 17:43:45] "GET / HTTP/1.1" 500 59
[2018-01-26 17:43:45,831] - Broken pipe from ('114.215.45.101', 59712)

Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[26/Jan/2018 19:22:57] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 60796
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[26/Jan/2018 19:22:57] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 500 59
[2018-01-26 19:22:57,239] - Broken pipe from ('94.102.49.174', 43917)

Invalid HTTP_HOST header: 'localhost.localdomain'. You may need to add u'localhost.localdomain' to ALLOWED_HOSTS.
[26/Jan/2018 19:42:23] "GET /. HTTP/0.0" 400 60027
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[26/Jan/2018 19:54:01] "GET / HTTP/1.1" 500 80792
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/site-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Not Found: /myAdmin/scripts/setup.php
[26/Jan/2018 20:27:26] "GET /myAdmin/scripts/setup.php HTTP/1.1" 404 3837
Invalid HTTP_HOST header: 'proxy.httpdaili.com'. You may need to add u'proxy.httpdaili.com' to ALLOWED_HOSTS.
[26/Jan/2018 20:54:30] "GET http://proxy.httpdaili.com/ip.asp?ip=111.231.93.28&dk=80 HTTP/1.1" 400 61343
Invalid HTTP_HOST header: 'localhost.localdomain'. You may need to add u'localhost.localdomain' to ALLOWED_HOSTS.
[26/Jan/2018 23:42:03] "HEAD /phpmyadmin/scripts/setup.php HTTP/1.0" 400 60466
Invalid HTTP_HOST header: '111.231.113.248:8000'. You may need to add u'111.231.113.248' to ALLOWED_HOSTS.
[27/Jan/2018 01:42:14] "GET / HTTP/1.1" 400 60376
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[27/Jan/2018 01:42:14] "GET / HTTP/1.1" 500 59
[2018-01-27 01:42:14,735] - Broken pipe from ('59.110.6.177', 44987)

Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[27/Jan/2018 01:49:34] "GET / HTTP/1.1" 500 80685
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[27/Jan/2018 01:57:08] "GET / HTTP/1.1" 500 80849
[27/Jan/2018 02:26:11] "GET /index_register_person/ HTTP/1.1" 200 4691
[27/Jan/2018 02:26:11] "GET /static/css/index.css HTTP/1.1" 404 1765
[27/Jan/2018 02:26:11] "GET /static/js/index.js HTTP/1.1" 404 1759
Not Found: /favicon.ico
[27/Jan/2018 02:26:11] "GET /favicon.ico HTTP/1.1" 404 3795
[27/Jan/2018 02:32:47] "GET /index_register_team/ HTTP/1.1" 200 5093
[27/Jan/2018 02:32:48] "GET /static/css/index.css HTTP/1.1" 404 1765
[27/Jan/2018 02:32:48] "GET /static/js/index.js HTTP/1.1" 404 1759
Performing system checks...

System check identified no issues (0 silenced).
January 24, 2018 - 15:24:07
Django version 1.11, using settings 'yuhuatai.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
The team has not registered
The team has not registered
The person has not registered
----------------------------------------
Exception happened during processing of request from (----------------------------------------
Exception happened during processing of request from'111.200.39.132',  ('111.200.39.132', 54112)
54113)
----------------------------------------
----------------------------------------
The person has not registered
The team has not registered
----------------------------------------
Exception happened during processing of request from ('113.96.219.243', 45500)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('121.51.14.23', 62848)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('14.116.133.170', 65248)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('157.255.172.125', 39194)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('98.25.203.167', 50057)
----------------------------------------
Performing system checks...

System check identified no issues (0 silenced).
January 27, 2018 - 02:48:44
Django version 1.11, using settings 'yuhuatai.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[27/Jan/2018 03:31:19] "GET / HTTP/1.1" 500 81229
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[27/Jan/2018 03:57:47] "GET / HTTP/1.1" 500 81043
Not Found: /ccvv
[27/Jan/2018 06:27:02] "GET /ccvv HTTP/1.1" 404 3774
Invalid HTTP_HOST header: '111.231.93.28    80    Open             :80'. The domain name provided is not valid according to RFC 1034/1035.
[27/Jan/2018 09:02:59] "GET /manager/html HTTP/1.1" 400 60709
Invalid HTTP_HOST header: '58.87.88.80:8000'. You may need to add u'58.87.88.80' to ALLOWED_HOSTS.
[27/Jan/2018 09:42:15] "GET / HTTP/1.1" 400 60318
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[27/Jan/2018 09:42:15] "GET / HTTP/1.1" 500 59
[2018-01-27 09:42:15,286] - Broken pipe from ('116.62.176.205', 1263)

Not Found: /phpmyadmin/index.php
[27/Jan/2018 09:48:33] "HEAD /phpmyadmin/index.php HTTP/1.1" 404 3823
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[27/Jan/2018 10:48:56] "GET / HTTP/1.1" 500 80618
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[27/Jan/2018 14:31:17] "GET / HTTP/1.1" 500 80754
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[27/Jan/2018 14:58:10] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 60794
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[27/Jan/2018 14:58:10] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 500 59
[2018-01-27 14:58:10,465] - Broken pipe from ('80.82.78.50', 51052)

Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib64/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 58, in get_response
    return debug.technical_404_response(request, e)
  File "/usr/lib64/python2.7/site-packages/django/views/debug.py", line 513, in technical_404_response
    return HttpResponseNotFound(t.render(c), content_type='text/html')
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 708, in resolve
    obj = self.var.resolve(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 849, in resolve
    value = self._resolve_lookup(context)
  File "/usr/lib64/python2.7/site-packages/django/template/base.py", line 911, in _resolve_lookup
    current = current()
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 183, in build_absolute_uri
    host=self.get_host(),
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 113, in get_host
    raise DisallowedHost(msg)
DisallowedHost: Invalid HTTP_HOST header: 'www.w5188.com'. You may need to add u'www.w5188.com' to ALLOWED_HOSTS.
[27/Jan/2018 15:23:28] "GET /static/UI_win7/js/login.js HTTP/1.1" 500 59
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[27/Jan/2018 16:09:58] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 60796
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[27/Jan/2018 16:09:58] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 500 59
[2018-01-27 16:09:58,172] - Broken pipe from ('94.102.49.174', 56633)

Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[27/Jan/2018 16:48:21] "GET / HTTP/1.1" 500 81227
Invalid HTTP_HOST header: 'wwww'. You may need to add u'wwww' to ALLOWED_HOSTS.
[27/Jan/2018 17:31:39] "HEAD /phpmyadmin/scripts/setup.php HTTP/1.1" 400 60475
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[27/Jan/2018 17:31:39] "HEAD /phpmyadmin/scripts/setup.php HTTP/1.1" 500 59
[2018-01-27 17:31:39,408] - Broken pipe from ('66.111.57.41', 54220)

Invalid HTTP_HOST header: '111.230.231.218:8000'. You may need to add u'111.230.231.218' to ALLOWED_HOSTS.
[27/Jan/2018 17:48:07] "GET / HTTP/1.1" 400 60376
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[27/Jan/2018 17:48:07] "GET / HTTP/1.1" 500 59
[2018-01-27 17:48:07,235] - Broken pipe from ('47.93.90.175', 14564)

Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[27/Jan/2018 18:41:41] "GET / HTTP/1.1" 500 80791
Not Found: /hndUnblock.cgi
[27/Jan/2018 23:42:33] "GET /hndUnblock.cgi HTTP/1.1" 404 3804
Not Found: /tmUnblock.cgi
[27/Jan/2018 23:42:33] "GET /tmUnblock.cgi HTTP/1.1" 404 3801
Not Found: /moo
[27/Jan/2018 23:42:34] "GET /moo HTTP/1.1" 404 3771
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[27/Jan/2018 23:42:36] "GET / HTTP/1.1" 500 80650
Not Found: /getcfg.php
[27/Jan/2018 23:42:37] "POST /getcfg.php HTTP/1.1" 404 3793
Not Found: /getcfg.php
[27/Jan/2018 23:42:38] "POST /getcfg.php HTTP/1.1" 404 3793
Invalid HTTP_HOST header: '111.230.5.40:80'. You may need to add u'111.230.5.40' to ALLOWED_HOSTS.
[28/Jan/2018 01:25:57] "GET / HTTP/1.1" 400 60082
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/usr/lib64/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
[28/Jan/2018 01:25:57] "GET / HTTP/1.1" 500 59
[2018-01-28 01:25:57,442] - Broken pipe from ('116.62.176.205', 63910)

Not Found: /getcfg.php
[28/Jan/2018 01:28:28] "GET /getcfg.php HTTP/1.1" 404 3792
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ticket/yuhuatai/piaowu/views.py", line 102, in index
    return render(request,'register.html',{})
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: register.html
[28/Jan/2018 01:50:52] "GET / HTTP/1.1" 500 80923
[2018-01-28 01:50:52,031] - Broken pipe from ('183.129.160.229', 38818)

Not Found: /phpmyadmin
[28/Jan/2018 03:06:47] "GET /phpmyadmin HTTP/1.1" 404 3792
